name: Expo PR Preview

on:
  pull_request:
    paths:
      - 'app/**'
      - 'components/**'
      - 'package.json'
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v18
        with:
          node-version: 18.x
          cache: 'npm'

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --branch pr-${{ github.event.number }}
          comment: true
          project-flavor: expo-go
